name: Generar JSON desde Supabase

on:
  schedule:
         -  cron: "*/30 0-5,12-23 * * 1-5"
         - cron: "0 * * * 6,0"   
  workflow_dispatch: 

jobs:
  llamar-funcion:
    runs-on: ubuntu-latest

    steps:
      - name: Llamar a función Edge de Supabase
        run: |
          curl -X POST "https://pwnysdqtryhpsxbwduxx.supabase.co/functions/v1/generar-json-productos" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE }}"
